events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/yt/ {
      proxy_pass https://inv.nadeko.net/;
      proxy_set_header Host inv.nadeko.net;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_ssl_server_name on;
      proxy_read_timeout 30s;
      proxy_connect_timeout 10s;
    }
  }
}